[package]
name = "hnproject"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
axum = "0.6.4"
minijinja = "0.30.2"
mongodb = "2.3.1"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full"] }